# Hackathon Portal Authentication
hackathon:
  username: PLEASE_REPLACE_ME
  password: PLEASE_REPLACE_ME

# SpringBoot: enable all endpoints (/mappings, /logfile, etc)
endpoints:
  enabled: true
management:
  security:
    enabled: false

# Properties used to fill in the Swagger Documentation Template
swagger:
  service:
    version: "1.0"
    title: ${spring.application.name}
    description: "A service that provides ..."
    termsPath: ""
    email: "your@email.com"
    licenceType: ""
    licencePath: ""

# Configuration of the local Web Server used by SpringBoot
server:
  tomcat:
    basedir: target/
    max-threads: 100
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

logging:
  file: ${APP_LOGS:${application.home:target}/logs}/application.log
  level:
    org.springframework: INFO
    com.expedia.eps.contentsystem.imageTaggingService.service: DEBUG

# Ribbon + Hystrix Configuration -- Enable uses of Feign for REST external services
ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 300000
  IsSecure: true
  eureka:
    enabled: false

# Enable Hystrix
feign:
  hystrix:
    enabled: true

hystrix.threadpool.default.coreSize: 12
hystrix.threadpool.default.maxQueueSize: 500
hystrix.threadpool.default.queueSizeRejectionThreshold: 500
hystrix.command.default.requestLog.enabled: true
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 50
hystrix.command.default.fallback.isolation.semaphore.maxConcurrentRequests: 20
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000

imageTaggingService:
  ribbon:
      listOfServers: services.expediapartnercentral.com:443

