kafka:
    servers:
        bootstrap: 127.0.0.1:9092

expedia:
    credentials:
        username: EQCEVETP
        password: 123456
    imageApi:
        url: https://int.services.expediapartnercentral.com
    productApi:
        url: https://int.services.expediapartnercentral.com/products
    retry:
        maxAttempts: 3
        intervalInMillis: 3000
